### ISSUE TITLE
Not found on UserService - createUser

### ISSUE THREAD

**Issue by PatrickDorneles** [Doctor-28/PizzariaJS#1]
On the createUser function, if it founds an user with the same email it appears to throw a NotFoundError.

**Comment by LeonardoBerlatto** [comment]
Oh, that's true :sweat_smile: . Actually, as I had just one custom error created, I just included that instead of an _EmailAlreadyInUseError_  for testing purposes. I'm going to fix it as soon as I create other custom errors and upgrade my User service.
